### ISSUE TITLE
How to train the model with different settings.

### ISSUE THREAD

**Issue by frozenburst** [andimarafioti/GACELA#1]
Could you please share how to train with other settings like:

sample rate (sr): 22050, 44100
with different mask width: 0.5 sec, 1.0 sec, 1.5sec, or maybe fuse?

I have tried with original settings with maestro dataset (41K subset with 10 seconds split each).
However, the training failed on too much recursive error on down-sample the sample rate.
"RecursionError: maximum recursion depth exceeded in comparison"
I fix this by import sys. And set the recursive limit larger. Then I got an OOM error.
After that, I tried on the original maestro segment with Mono (Not stereo).
I got the error with "ValueError: Window is too long".

I could only train the settings with sr: 44100 and signal split: [480, 64, 480], which means the gap only be length around 0.4 sec.
(On my 10 seconds split and Mono dataset)

Moreover,
I want to enlarge the gap to be like [426, 172, 426] but it fails. 
(172 might be 1 sec on sr: 44100 and I think the input shape should be 1024 in total?)
Could you please share how to edit the parameter for training other lengths of mask gap?

Other question:
1. In my opinion, the method seems could only train on the input with a mask in the middle, instead of a mask at the beginning, or the end? 
2. The input image always needs the width to be 1024, which means under the hop size "256", the input image needs at least 11.9 sec on sr: 22050, or 5.95 sec on sr: 44100.
3. Due to the reason above, the method can not apply to audio segments with a length of 5 sec like the ESC-50 dataset under sr: 44100, am I right?
4. The training seems to be only on constant mask width, if we want different mask widths like 0.5 sec and 1 sec, we need to train two models or more?

Appreciate the good work on audio inpainting. 
If there is any misunderstanding about the works, just correct me without hesitation.

**Comment by frozenburst** [comment]
Now, I found that the input image should be 512, 1024 or 2048 for gap in 32, 64, 128. Which discovered from checkpoints.
I can now train on settings like [240, 32, 240] with sr: 44100 on my 10 seconds split datasets (input shape:[1, 512, 512], batch size: 32 and window_size in trainDataset is 512 as well).

Well, it is too much to consider with the parameter settings...
I just want to know how could I reproduce the result with your model under such settings:

sr: 44100, mask: 0.2, 0.4, 0.6, 0.8, 1.0 seconds on maestro with 10 seconds split.
sr: 22050, mask: 0.2, 0.4, 0.6, 0.8, 1.0 seconds on ljspeech with 10 seconds split.

also the test.py to output the results (waveform or spectrogram) on the test split.

Otherwise,
If the request bothers too much, provides the settings train on 1 seconds mask only is great as well.

**Comment by andimarafioti** [comment]
Hi Frozenburst, I'm sorry for the delay. 

To do a custom training such as what you are looking for, there is going to be some coding involved. To get an idea for how your file will look like, there is a folder with different training examples, these are all the options we used for the paper (https://github.com/andimarafioti/GACELA/tree/master/train%20paper%20networks) I recommend starting there. 

For example, for input image 512, gap size 32 (375 ms), you can follow: 
https://github.com/andimarafioti/GACELA/blob/master/train%20paper%20networks/main_realData_short_2.py
or for input image 1024, gap size 32, there is: 
https://github.com/andimarafioti/GACELA/blob/master/train%20paper%20networks/main_realData_short.py
or for input image 2048, gap size 128 (1500 ms), there is: 
https://github.com/andimarafioti/GACELA/blob/master/train%20paper%20networks/main_realData_long_2.py

You can also try with more standard options with the train.py file provided in the main folder of the repository. That one, however, doesn't support you changing the window size (you will always have 1024 samples) or the sampling rate.

**Comment by andimarafioti** [comment]
Response to your other questions:

1. The method can also be used to generate information to one of the sides. You can try to use "split = (960, 64, 0)"
2. The image doesnt "need" to be 1024. Check for example https://github.com/andimarafioti/GACELA/blob/master/train%20paper%20networks/main_realData_long_2.py and https://github.com/andimarafioti/GACELA/blob/master/train%20paper%20networks/main_realData_short_2.py . With window sizes 512 and 2048. 
3. The only thing really stopping you from using this method on 5 second gaps at 44.1 kHz is fitting the whole thing on GPU. 
4. The training is on constant mask sizes. In our experiments, we trained different models for different gap lengths.

**Comment by andimarafioti** [comment]
For testing, I hope that this notebook is enough to get you started (https://github.com/andimarafioti/GACELA/blob/34649fb01bdecbcb266db046a8b9c48c141f16e1/Test%20GACELA.ipynb). Custom models will require custom tests

**Comment by andimarafioti** [comment]
Regarding the errors you had, I don't know why you got the recursion error, that looks strange. The OOM is probably due to you trying to fit too much data into your gpu. If you can provide a more detailed traceback maybe I can help you further.

**Comment by frozenburst** [comment]
Thanks for the reply.

As summary, the settings on image width 512, 1024 or 2048 for gap in 32, 64, 128 is all we can try on this model right?
Which means the gap under settings sr 22050,
32 (375ms) need at least 512 (5.94 sec) as input,
64 (750ms) need at least 1024 (11.88 sec) as input,
128 (1.5ms) need at least 2048 (23.76 sec) as input.
This also make the gap 64, 128 cannot work on the LJ-Speech dataset which is combined with 10 seconds split only.
For question 3, what I mean is that all the segments in the Esc-50 dataset is only 5 seconds. Which is too short for this model to apply on.


Above all, the model cannot work on the settings I want like:

- sr: 44100, mask: 0.2, 0.4, 0.6, 0.8, 1.0 seconds on maestro with 10 seconds split.
- sr: 22050, mask: 0.2, 0.4, 0.6, 0.8, 1.0 seconds on ljspeech with 10 seconds split.

Because the mask length is only available with certain length 0.375 sec, 0.75 sec, and 1.5 sec under sr: 22050.
Is there anything wrong within my understandings?

**Comment by andimarafioti** [comment]
Partially. There is nothing stopping you from using image width 256 or 4096. I would try to keep with multiples of two for the total image used as input, and for the output of the generator, but otherwise there are no obvious restrictions. You can also try to use a higher sampling rate, you just need to make a custom training file with that sampling rate. 

For the Esc-50, you can also pad the signals with zeros, results should be ok. 

The settings you want are going to be hard to get with this implementation.

**Comment by frozenburst** [comment]
Yeah, that was what I found so I asked for help if there are any existing scripts related.
There are too many parameters in the scripts to tune for custom settings.
I might consider another way out or just give up. Thanks for providing the details.

**Comment by andimarafioti** [comment]
No problem, I agree that the training script has a lot of parameters, that's why we provide the simple training script with just a few, but then those might be too little. Hope you find a way around!
